services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/lti-grader
      - ENCRYPTION_KEY=dev_encryption_key_12345
      - LTI_KEY=dev_lti_key_12345
      - PORT=3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
